name: Deobfuscate

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  deobfuscate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run deobfuscator
        run: node index.js

      - name: Push changes
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add key.key
          git commit -m "chore: update deobfuscated JS [auto]" || echo "No changes"
          git push
